workflows:
  android-release:
    name: Android Release Build

    environment:
      java: 17

    scripts:
      - chmod +x ./gradlew
      - ./gradlew clean
      - ./gradlew assembleRelease

      - name: Find APK Files
        script: |
          echo "Searching APK..."
          find . -name "*.apk"

          echo "Searching AAB..."
          find . -name "*.aab"

    artifacts:
      - "**/*.apk"
      - "**/*.aab"