workflows:
  android-workflow:
    name: Android Build

    environment:
      java: 17

    scripts:
      - name: Clean project
        script: ./gradlew clean

      - name: Build APK
        script: ./gradlew assembleRelease

    artifacts:
      - "**/outputs/**/*.apk"
