workflows:
  android-workflow:
    name: Android Build
    environment:
      java: 17
    scripts:
      - name: Build APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/*.apk